CREATE TABLE ORDER_STEP (
	ID INT PRIMARY KEY,
	STEP_NAME VARCHAR(100),
	START_DATE	DATETIME,
	END_DATE DATETIME,
	STATUS VARCHAR(10),
	ORDER_NUMBER INT ,
	FOREIGN KEY(ORDER_NUMBER) REFERENCES CUSTOMER_ORDER(ID)
);