CREATE TABLE PRODUCT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CATALOG_ID INT,
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    ORDER_NUMBER INT,
    STATUS VARCHAR(10),
    CUSTOMER_ID INT REFERENCES CUSTOMER.ID,
    PARENT_PRODUCT INT REFERENCES PRODUCT.ID
    );